language: python

services:
  - mongodb
  - postgresql

sudo: false

matrix:
    fast_finish: true

python:
  - "3.5"

install: "pip install -r requirements.txt"

before_script:
  - createuser ethereumscanner -d -l -w
  - createdb ethereumscanner -O ethereumscanner
  - ./manage.py migrate

script: ./manage.py test

notifications:
    email: true
#
#addons:
#  sonarqube: true

cache:
  directories:
    – $HOME/.m2
    – $HOME/.sonar/cache

env:
  global:
    - secure: a_very_long_hash_string_here
jdk: oraclejdk8
language: java
script: mvn clean install sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN