language: python

services:
  - mongodb
  - postgresql

sudo: false

matrix:
    fast_finish: true

python:
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - createuser ethereumscanner -d -l -w
  - createdb ethereumscanner -O ethereumscanner
  - ./manage.py migrate

script:
  - ./manage.py test
  - coverage run --source=. manage.py test


notifications:
    email: true

after_success:
  coveralls