language: python

services:
  - mongodb
  - postgresql

sudo: false

matrix:
    fast_finish: true

python:
#  - "3.3"
#  - "3.4"
  - "3.5"

install: "pip install -r requirements.txt"

before_script:
  - createuser ethereumscanner -d -l -w
  - createdb ethereumscanner -O ethereumscanner

script: ./manage.py test

notifications:
    email: false